blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import BlogPostUpdateView

urlpatterns = [
    path('',views.bloghome,name='bloghome'),
    path('/createblog',views.createblog,name='createblog'),
    path('/saveblog',views.saveblog,name='saveblog'),
    path('/postcomment',views.PostComment,name='postcomment'),
    path('/Blogsearch',views.Blogsearch,name='Blogsearch'),
    path('/userblogposts',views.userblogposts,name='userblogposts'),
    path('/deleteblogpost',views.deleteblogpost,name='deleteblogpost'),
    path('/deletethepost',views.deletethepost,name='deletethepost'),
    path('/<str:slug>/update',BlogPostUpdateView.as_view(),name='blogpost-update'),
    path('/<str:slug>',views.blogpostview,name='blogpostview'),
]

listofposts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('',views.listofposts,name='listofposts'),  
]

prefixpostfix/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


admin.site.site_header = "PREFIXPOSTFIX ADMIN"
admin.site.site_title = "ADMIN-TANMOY"
admin.site.index_title = "WELCOME-ADMIN-TANMOY"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),                     
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

listofposts/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.shortcuts import render,HttpResponse,redirect,reverse
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Post(models.Model):
    postsno = models.AutoField(primary_key=True)
    parentname = models.CharField(max_length=200)
    title = models.CharField(max_length=255)
    content = RichTextUploadingField(blank=True,null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    slug = models.CharField(max_length=200)
    timeStamp = models.DateTimeField(null = True,blank=True,default=now)
    
    def __str__(self):
        return self.title + ' by ' + str(self.author)
    def get_absolute_url(self):
        return redirect('/')
        

class Comment(models.Model):
    commentsno = models.AutoField(primary_key = True)
    newcomment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return self.newcomment[0:20]+'...' + ' -by- ' +str(self.user)

listofposts/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Post
from home.models import Product
from django.core.paginator import Paginator

# Create your views here.
def listofposts(request):
    query = request.GET.get('query')
    selectedPosts = Post.objects.filter(parentname=query).order_by('-timeStamp')
    paginator = Paginator(selectedPosts, 15)
    # now no need to render selectedPosts now page_obj will work as selected posts
    # context={'selectedPosts':selectedPosts,'query':query}  
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={'query':query,'page_obj':page_obj}        

    return render(request,'section/section.html',context)

templates/listofposts/post_form.html
{% extends 'base.html' %}
{% block titile %}
Add new post
{% endblock titile %}
{% comment %} form for post update {% endcomment %}
{% block body %}
{% if user.is_authenticated %}

<div class="container mt-5 mb-5" style="text-align: center;">
    <form method="post" style="font-family: 'El Messiri', sans-serif; font-size: 35px;">
        {% csrf_token %}
        {{ form.media }}
        <div class="container" style="width: 78%;">
            <h4>Title</h4>
            <span>{{form.title}}</span>
            <h4 class='mt-4'>Add a main field name in
                which under you want to add this post</h4>
            <span>{{form.parentname}}</span>
            <div class="mt-4 mb-5">
                <h4 class='mb-2' >You write the best :)</h4>
                {{form.content}}
            </div>
            <h4 class='mt-4'>Edit The Url Slug (We recommend to give related to Title)</h4>
            <span>{{form.slug}}</span>
        </div>
        {% comment %} {{ form.as_p }} {% endcomment %}
        <button class='btn btn-success btn-lg my-3' type="submit">Update</button>
    </form>
</div>
<style>
    input::-webkit-input-placeholder {
        font-size: 15px;
    }
    #id_title{
          width: 80%;
          padding: 5px 10px;
          margin: 2px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
          font-size: 25px;
    }
    #id_parentname{
          width: 80%;
          padding: 5px 10px;
          margin: 2px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
          font-size: 25px;
    }
    #id_slug{
          width: 80%;
          padding: 5px 10px;
          margin: 2px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
          font-size: 25px;
    }
</style>

{% else %}
<h1>Please login to access this page</h1>
{% endif %}
{% endblock body %}