blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import BlogPostUpdateView

urlpatterns = [
    path('',views.bloghome,name='bloghome'),
    path('/createblog',views.createblog,name='createblog'),
    path('/saveblog',views.saveblog,name='saveblog'),
    path('/postcomment',views.PostComment,name='postcomment'),
    path('/Blogsearch',views.Blogsearch,name='Blogsearch'),
    path('/userblogposts',views.userblogposts,name='userblogposts'),
    path('/deleteblogpost',views.deleteblogpost,name='deleteblogpost'),
    path('/deletethepost',views.deletethepost,name='deletethepost'),
    path('/<str:slug>/update',BlogPostUpdateView.as_view(),name='blogpost-update'),
    path('/<str:slug>',views.blogpostview,name='blogpostview'),
]

prefixpostfix/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


admin.site.site_header = "PREFIXPOSTFIX ADMIN"
admin.site.site_title = "ADMIN-TANMOY"
admin.site.index_title = "WELCOME-ADMIN-TANMOY"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),                     
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.shortcuts import render,HttpResponse,redirect,reverse
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class BlogPost(models.Model):
    serialnumber = models.AutoField(primary_key=True)
    blogtitle = models.CharField(max_length=255)
    Thumbnail_image = models.ImageField(upload_to="blog/images/blog_thumbnail_images",blank=True)
    blog_des = models.CharField(max_length=500,blank=True)
    blogcontent = RichTextUploadingField(blank=True,null=True)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    slug = models.CharField(max_length=200)
    time = models.DateTimeField(null = True,blank=True,default=now)

    def __str__(self):
        return self.blogtitle + ' by ' + str(self.writer)
    def get_absolute_url(self):
        return redirect('/blog')    

class BlogComment(models.Model):
    commentsno = models.AutoField(primary_key = True)
    newcomment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return str(self.newcomment) + ' by ' + str(self.user)
          

blog/forms.py
from django import forms 
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import BlogPost


class blogcreateform(forms.ModelForm):
    blogtitle = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'Blog title here...',
            
        }
    ))
    blog_des = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'Add a short blog description...',
            
        }
    ))
    class Meta:
        model = BlogPost
        fields = [
            'blogtitle',
            'blog_des',
            'blogcontent',
        ]

        

blog/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import BlogPost,BlogComment
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
from . forms import blogcreateform

from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.
def bloghome(request):
    blogs = BlogPost.objects.all().order_by('-time')
    paginator = Paginator(blogs, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context ={'page_obj':page_obj}
    return render(request,'blog/bloghome.html',context)

@login_required(login_url='/loginsignup')
def createblog(request):
    context ={'form':blogcreateform()} 
    return render(request,'blog/blogcreate.html',context)

@login_required(login_url='/loginsignup')
def saveblog(request):
    form = blogcreateform(request.POST,request.FILES)
    if form.is_valid():
        writer = request.user
        blogtitle = request.POST.get('blogtitle')
        slug = blogtitle.replace(" ", "+")
        Thumbnail_image = request.FILES['thumbimage']
        blog_des = request.POST.get('blog_des')
        blogcontent = request.POST.get('blogcontent')
        newblog = BlogPost.objects.create(writer=writer,blogtitle=blogtitle,slug=slug,Thumbnail_image=Thumbnail_image,
        blog_des=blog_des,blogcontent=blogcontent)
        newblog.save()
        messages.success(request,'Your Story Has Been Posted Successfully :)')
    return redirect('/blog')

def blogpostview(request,slug):
    blogpost = BlogPost.objects.filter(slug=slug).first()
    comments = BlogComment.objects.filter(post=blogpost).order_by('-timestamp')
    context = {'blogpost': blogpost, 'comments':comments}
    return render(request,'blog/viewblog.html',context)

@login_required(login_url='/loginsignup')
def PostComment(request):
    if request.method == 'POST':
        comments = request.POST.get('comment')
        user = request.user
        postSno = request.POST.get('postSno')
        post = BlogPost.objects.get(serialnumber=postSno)
        comment = BlogComment(newcomment=comments,post=post,user=user)
        comment.save()
    return redirect(f'/{post.slug}')    

def Blogsearch(request):
    searchquery = request.GET['search']
    if len(searchquery)>200:
        allposts = BlogPost.objects.none()
    if len(searchquery)< 4:
        allposts = BlogPost.objects.none()
        messages.error(request,'Please enter more than 4 characters')
        redirect('/')
    else:    
        allpoststitle = BlogPost.objects.filter(blogtitle__icontains=searchquery)
        allpostscontent = BlogPost.objects.filter(blogcontent__icontains=searchquery)
        allposts = allpoststitle.union(allpostscontent)
        paginator = Paginator(allposts, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'page_obj':page_obj,'search':searchquery}
        return render(request,'blog/blogsearch.html',context) 
    return render(request,'blog/blogsearch.html')


def userblogposts(request):
    allblogposts = BlogPost.objects.filter(writer=request.user)
    paginator = Paginator(allblogposts, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={'page_obj':page_obj}
    return render(request,'blog/userallblogposts.html',context)  


@login_required(login_url='/loginsignup')
def deleteblogpost(request):
    if request.method == 'POST':
        postid = request.POST.get("deletepostid")
        posttitle = BlogPost.objects.filter(serialnumber=postid).first()
        context = {'deletepostid': postid,'posttitle':posttitle}
        return render(request, 'blog/blogdeleteconfirm.html',context)
    else:
        messages.error(request,'ERROR TO DELETE POST')
        return redirect('/blog')       

@login_required(login_url='/loginsignup')
def deletethepost(request):
    if request.method == 'POST':
        deletepostconfirmed = request.POST.get('deletepostconfirmed')
        BlogPost.objects.filter(serialnumber = deletepostconfirmed).delete()
        messages.success(request,'Your post has been Deleted')
        return redirect('/blog')
    else:
        messages.error(request,'ERROR TO DELETE POST')
        return redirect('/blog')                  

class BlogPostUpdateView(LoginRequiredMixin, UserPassesTestMixin,UpdateView):
    model = BlogPost
    fields = ['blogtitle','Thumbnail_image','blog_des','blogcontent','slug','time']
    success_url = '/blog/userblogposts'
    login_url = 'loginsignup'
    def form_valid(self, form):
        form.writer = self.request.user
        return super().form_valid(form)
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.writer:
            return True
        return False                

templates/blog/blogcreate.html
{% extends 'base.html' %}
{% block title %}Create New Blog Post
{% endblock title %}

{% block body %}



<div class="container mt-5 mb-5" style="text-align: center;">
    <form action="saveblog" method="post" enctype="multipart/form-data" style="font-family: 'El Messiri', sans-serif;">
        {% csrf_token %}
        {{ form.media }}
        <div class="container" style="width: 78%;">
            <h4>Give Blog Title</h4>
            <span>{{form.blogtitle}}</span>
            <h4 class='mt-3'>Give Blog Description</h4>
            <span>{{form.blog_des}}</span>
            <h4 class=' mt-3 mb-3' style="font-size: 25px;">Choose a Thumbnail Image</h4>
            <input class="btn btn-sm ml-5 " type="file" name="thumbimage" accept="image/*" required><br>
            <div class="mt-4 mb-5">
                <h4 class='mb-2' >You write the best :)</h4>
                <span>{{form.blogcontent}}</span>
            </div>
        </div>
        {% comment %} {{ form.as_p }} {% endcomment %}
        <input class='btn btn-success btn-lg' type="submit" href="saveblog" value="Save Blog">
    </form>

</div>

{% endblock body %}

templates/blog/blogdeleteconfirm.html
{% extends 'base.html' %}
{% block title %}
Confirm Delete Operation
{% endblock title %}

{% block body %}

<div class="container" style="text-align: center; width: 60%; font-family: 'El Messiri', sans-serif;">
        <h2 class= "mt-5 pt-5">
            Are you sure you want to delete this blog post?
        </h2><br>
        <h4 class="mt-3">{{posttitle.blogtitle}}</h4>
        <form action="deletethepost" method="POST">
            {% csrf_token %}
            <div class="mt-5">
            <button type="submit" class="btn btn-danger mr-3">Confirm</button>
            <a type="submit" class="btn btn-success" href="/blog">Back To Home</a>
            </div>
            <input type="hidden" name='deletepostconfirmed' value="{{deletepostid}}">
        </form>
        
</div>
{% endblock body %}

templates/blog/bloghome.html
{% extends 'base.html' %}
{% block title %}PrefixPostfix Blog - Learn better, Learn Smatter
{% endblock title %}

{% block body %}
<link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
<div style="font-family: 'El Messiri', sans-serif; font-weight:400;">



  <div class="jumbotron shadow-lg" style="background: url('static/img/jumbocoverfinal1.jpg') no-repeat center center;width:100%;
  height: 425px; border-radius: 0px;
  background-size:cover;">
    <h4 style="float: left; margin-top: 3%; font-family:'Special Elite', cursive; font-size:40px; color:gray;">
      {{request.user}},</h4>
  </div>


<div class="container" style="text-align: center; width:80%;">
  <form method="get" action="/blog/Blogsearch" class="form-inline my-lg-4">
    <input class="form-control mr-1 ml-4" name="search" id="search"
        style="background-color: transparent; outline: none; border: none;border-bottom: 1px solid green; color: black; border-radius: 0; box-shadow: none;
        width: 90%;"
        type="search" placeholder="Search Blog Posts Here...." aria-label="Search">
    <button class="btn btn-outline-success my-2 mr-4 my-sm-0" style="border:none; border-radius: 10rem;"
        type="submit">
        <svg class="bi bi-search" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
            <path fill-rule="evenodd"
                d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
        </svg>
    </button>

  </form>
</div>


  <div class="container" style="width:80%">

    <div class="row">
      <div class='col-md-10' style="text-align: left;">
        <h1 class="mt-3">Most Recent Posts</h1>
      </div>
      <div class="col-md-2" style="text-align:right;">

        <a class='btn btn-info mb-5 mt-2' type="submit" href="blog/createblog">Create Post</a>
      </div>
    </div>


    <div class="row">
      {% for blog in page_obj %}
      <div class="col-md-12">
        <div class="row no-gutters overflow-hidden flex-md-row mb-4 shadow-lg h-md-250 position-relative"
          style="word-wrap: break-word;">
          <div class="col-auto d-none d-lg-block">
            <img class="bd-placeholder-img p-0 m-0" width="300" height="250" role="img"
              src="{{blog.Thumbnail_image.url}}">

            </img>
          </div>
          <div class="col pr-0 pt-4 pb-4 pl-4 d-flex flex-column position-static">
            <a class="d-inline-block " href="blog/{{blog.slug}}">
              <h2>{{blog.blogtitle}}</h2>
            </a>
            <p class="m-0" style="font-size:18px;">{{blog.blog_des|truncatechars:100}}</p>
            <div class="mb-1 text-muted"> <small>{{blog.time}}</small></div>
            <a href="blog/{{blog.slug}}" class="btn btn-success">Continue reading</a>
          </div>
          <div class="col-md-2 d-none d-sm-block" width="170" height="250"
            style="padding-right: 0px; padding-left: 0px;">
            <div class="container mt-2" style="text-align: center;">

              <img class="bd-placeholder-img rounded-circle mt-5" width="80" height="80"
                src="{{blog.writer.userdata.profile_pic.url}}" alt=""> <br>
              <small>Written by,</small><br>
              <p>@{{blog.writer.username}}</p>

            </div>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  


<!-- paginator -->
    <div style="font-family: sans-serif">
      <nav aria-label="...">
        <ul class="pagination pagination-sm justify-content-end">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" style="color:#3C4146; border-color:darkgray"
              href="?page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
  
          {% endif %}
  
          {% for i in page_obj.paginator.page_range %}
          {% if i == page_obj.number %}
          <li class="page-item active"><a class="page-link" style="background-color:green; border:none;"
              href="?page={{i}}">{{i}}</a></li>
  
          {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
          <li class="page-item mx-1"><a class="page-link" style="border-radius:5px; border-color:darkgray;"
              href="?page={{i}}">
              <font color='#3C4146'>{{i}}</font>
            </a></li>
  
          {% endif %}
          {% endfor %}
  
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" style="color:#3C4146; border-color:darkgray"
              href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}
        </ul>
      </nav>
   </div>
  

  </div>
</div>


{% endblock body %}

templates/blog/blogpost_form.html
{% extends 'base.html' %}
{% block title %}Create New Blog Post
{% endblock title %}

{% block body %}



<div class="container mt-5 mb-5" style="text-align: center;">
    <form method="post" style="font-family: 'El Messiri', sans-serif;">
        {% csrf_token %}
        {{ form.media }}
        <div class="container" style="width: 78%;">
            <h4>Blog Title</h4>
            <span>{{form.blogtitle}}</span>
            <h4 class='mt-3'>Blog Description</h4>
            <span>{{form.blog_des}}</span>
            <h4 class=' mt-3 mb-3' style="font-size: 25px;">Choose a Thumbnail Image</h4>
            
            {{form.Thumbnail_image}}
            <div class="mt-4 mb-5">
                <h4 class='mb-2' >You write the best :)</h4>
                <span>{{form.blogcontent}}</span>
            </div>
        </div>
        <h4 class='mt-3'>Edit The Url Slug (We recommend to give related to Title)</h4>
            <span>{{form.slug}}</span><br>
        {% comment %} {{ form.as_p }} {% endcomment %}
        <button class='btn btn-success btn-lg my-3' type="submit">Update</button>
    
    
    <style>
          #id_blogtitle{
          width: 80%;
          padding: 5px 10px;
          margin: 2px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
          font-size: 25px;
          }
          #id_blog_des{
          width: 80%;
          padding: 5px 10px;
          margin: 2px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
          font-size: 25px;
          }
          #id_slug{
          width: 80%;
          padding: 5px 10px;
          margin: 2px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
          font-size: 25px;
          }
    
    </style>
    
    
    </form>

</div>

{% endblock body %}

templates/blog/blogsearch.html
{% extends 'base.html' %}
{% block title %}
Blog Search results
{% endblock title %}

{% block body %}



<div class="container pt-3" style="width: 75%;">

    <div class="my-3 p-3 bg-white rounded shadow-lg">
        <h2 class="border-bottom border-gray pb-3 mb-0">Search Results:</h2>

        {% if page_obj|length < 1 %}
        
            <p class="mt-4">
            No result found<br>
            Your search query: <b>{{serchquery}}</b> did not did not match any documents <br>
            Suggestions:
            <ul>
            <li>Try different Keywords.</li>
            <li>Make sure that all words are spelled correctly.</li>
            <li>Try more general Keywords.</li>
            <li>Try fewer Keyqords.</li>
            </ul>
            </p>

        {% endif %} 

        {% for post in page_obj %}
        
        <div class="media text pt-2">
            {% comment %} <svg class="bi bi-shift-fill mt-2 mr-4" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M7.27 2.047a1 1 0 0 1 1.46 0l6.345 6.77c.6.638.146 1.683-.73 1.683H11.5v3a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-3H1.654C.78 10.5.326 9.455.924 8.816L7.27 2.047z" />
            </svg> {% endcomment %}

            <h3 class="media-body pb-0 mb-0 border-bottom border-gray">
                <a href='{{post.slug}}' class="d-block text-gray-dark">{{post.blogtitle}}</a>
                {% comment %} <small>{{post.content| truncatechars:300}}</small> {% endcomment %}
                <p class="pt-1 pb-0 mb-1 " style="font-size: small;">@{{post.writer}}</p>
             
            </h3>
        </div>

        {% endfor %}

    </div>
</div>


 <!-- paginator section -->

 <div>
    <nav aria-label="...">
      <ul class="pagination pagination-sm justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" style="color:#3C4146; border-color:darkgray"
            href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>

        {% endif %}

        {% for i in page_obj.paginator.page_range %}
        {% if i == page_obj.number %}
        <li class="page-item active"><a class="page-link" style="background-color:green; border:none;"
            href="?page={{i}}">{{i}}</a></li>

        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
        <li class="page-item mx-1"><a class="page-link" style="border-radius:5px; border-color:darkgray;"
            href="?page={{i}}">
            <font color='#3C4146'>{{i}}</font>
          </a></li>

        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" style="color:#3C4146; border-color:darkgray"
            href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% endif %}
      </ul>
    </nav>

  </div>





{% endblock body %}

templates/blog/userallblogposts.html
{% extends 'base.html' %}
{% block title %}User All Blog Posts
{% endblock title %}


{% block body %}


<div class="container mt-5 " style="width:80%;">
  {% for post in page_obj %}

  <div class="my-3 p-3 bg-white rounded shadow-lg">

    <div class="media text pt-1 ml-4">

      <h3 class="media-body pb-0 mb-0 ">
        <a href='{{post.slug}}' class="d-block text-gray-dark" style="font-size: 21px">{{post.blogtitle}}</a>
        <p class="pt-1 pb-0 mb-1 " style="font-size: small;">@{{post.writer}}</p>

      </h3>
        <form action="deleteblogpost" method="post">
        {% csrf_token %}
        <input type="hidden" id="deletepostid" name="deletepostid" value="{{post.serialnumber}}">
        <a href="{{post.slug}}/update" class='btn btn-warning m-1'>Edit</a>
        <button type="submit" class='btn btn-danger m-1'>Delete</button>
        </form>
      
    </div>
  </div>


  {% endfor %}



  <!-- paginator section -->

  <div>
    <nav aria-label="...">
      <ul class="pagination pagination-sm justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" style="color:#3C4146; border-color:darkgray"
            href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>

        {% endif %}

        {% for i in page_obj.paginator.page_range %}
        {% if i == page_obj.number %}
        <li class="page-item active"><a class="page-link" style="background-color:green; border:none;"
            href="?page={{i}}">{{i}}</a></li>

        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
        <li class="page-item mx-1"><a class="page-link" style="border-radius:5px; border-color:darkgray;"
            href="?page={{i}}">
            <font color='#3C4146'>{{i}}</font>
          </a></li>

        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" style="color:#3C4146; border-color:darkgray"
            href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% endif %}
      </ul>
    </nav>

  </div>

</div>

{% endblock body %}

templates/blog/viewblog.html
{% extends 'base.html' %}
{% block title %}
{{blogpost.blogtitle}}
{% endblock title %}

{% block body %}
<!-- good font
style="font-family: 'El Messiri', sans-serif; font-size: 40px;" -->


<div class="container" style="width:65%; padding-top: 60px;">


    <div class="blog-post">
        <h2 class="blog-post-title"style="font-family: 'El Messiri', sans-serif; font-size: 35px;">{{blogpost.blogtitle}}</h2>
        <small class="blog-post-title"><img class="ml-1 mt-2 mr-1" style="height:40px; width:40px; border-radius:15%;"
            src='{{blogpost.writer.userdata.profile_pic.url}}' alt="user image">{{blogpost.writer.username}}</small>
        <small><p class="blog-post-meta mt-1">{{blogpost.time}}</p></small>
        
        <hr>
        <div>
            <p>{{blogpost.blogcontent|safe}}</p>
            <style>
                    img {
                             max-width: 100%;
                             max-height: 100%;
                             object-fit: contain;
                             height: inherit !important;
                        }
            </style>
            </div>
        <hr>
    </div>

    <div class="container">
        

        <div class="col-md-12 col-sm-12 col-lg-12 my-4" style="align-content: center;">

            <div
                class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-50 position-relative">
                <div class="col p-3 d-flex flex-column position-static ">

                    <form action='postcomment' method='post'>
                        {% csrf_token %}
                        <div class="row">

                            <div class="col-md-1 p-2">
                            {% if request.user.is_authenticated %}
                                <img class="ml-2 my-1" style="height:35px; width:35px; border-radius:15%;"
                                    src='{{request.user.userdata.profile_pic.url}}' alt="user image">{% endif %}
                                </div>

                            <div class="col-md-11 p-2">
                                <textarea type="text" placeholder="Write a Response..."
                                    style="border:none; border-radius:0px; box-shadow:none; outline:none;"
                                    class="form-control" name='comment' id="comment"
                                    aria-describedby="comment"></textarea>
                            </div>

                            <input type="hidden" name="postSno" value="{{blogpost.serialnumber}}">

                        </div>
                        <button type="submit" style="border-radius: 0%;font-family: 'El Messiri', sans-serif; font-size: 18px;"
                            class="btn btn-outline-success btn-lg btn-block"><b>Submit Response</b></button>
                    </form>

                </div>
            </div>

        </div>
        <h2 style="font-family: 'El Messiri', sans-serif; font-size: 25px;" >Responses</h2>
        <div class="row my-3">
            {% for comment in comments %}
            <div class="col-md-12" style="align-content: center;">

                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-2 shadow-sm h-md-50 position-relative">
                    <div class="col p-3 d-flex flex-column position-static ">
                        <div class="row">
                        <div class="col-md-1"><img class="ml-2 mt-2" style="height:35px; width:35px; border-radius:15%;"
                                src='{{comment.user.userdata.profile_pic.url}}' alt="user image"></div>
                        <div class="col-md-11" style="word-wrap: break-word;">
                            <font size="2">@{{comment.user.username}}</font><br>{{comment.newcomment}}
                        </div>
                    </div>
                </div>
                </div>
            </div>
            {% endfor %}
            
        </div>

    </div>
</div>

    {% endblock body %}